server:
  error:
    include-stacktrace: ON_PARAM
spring:
  datasource:
    url: jdbc:mysql://localhost:3303/spring
    username: root
    password: 92470
    name: Mysql
  jpa:
    hibernate:
      ddl-auto: update
