server:
  error:
    include-stacktrace: ON_PARAM
spring:
  datasource:
    url: jdbc:mysql://localhost:3303/training
    username: root
    password: 92470
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    sql: trace

